// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_vip_pres");
	self.voice = "american";
}

precache()
{
	precacheModel("body_complete_sp_vip_pres");
}
